//! The canonical ICD-10 / CPT seed catalog.
//!
//! This table is the single source of truth for the code-to-description
//! mapping that clinical contracts and off-chain tooling resolve. It was
//! previously a 950-line literal block inside
//! `contracts/clinical_nlp/src/icd_cpt_codes.rs`, where only that one
//! contract could see it (issue #1629).
//!
//! Every field is a `&'static str` / integer literal so the table costs
//! nothing on-chain: a contract copies it into host storage once and off-chain
//! tools read it directly, with no serialization step and no second mapping
//! to drift.
//!
//! Invariants asserted by `icd_cpt::validate` and covered by the crate tests:
//!
//! * `code` is unique across the whole catalog.
//! * `code_type` matches the shape of `code`: `Icd10` => `X00` with an
//!   optional `.N` suffix, `Cpt` => five digits with an optional trailing
//!   modifier letter.
//! * No entry lists the same keyword twice. A keyword *may* be shared by two
//!   entries — `"pacemaker"` is evidence for both a pacemaker in the patient's
//!   history (`Z95.0`) and pacemaker implantation (`33208`).
//! * `description` and `category` are non-empty.
//! * `keywords` is non-empty and lowercase, and no entry repeats one.
//! * `related_codes` never references the entry itself.
//! * `effective_date <= expiration_date` whenever an expiry is set.

use crate::CatalogCode;
use crate::CodeType;

/// The seed catalog: 20 ICD-10 diagnosis codes and 16 CPT procedure codes.
pub const CATALOG: &[CatalogCode] = &[
    CatalogCode {
        code: "I10",
        code_type: CodeType::Icd10,
        description: "Essential (primary) hypertension",
        category: "Diseases of the circulatory system",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["I11.9", "I12.9"],
        keywords: &["hypertension", "high blood pressure", "htn", "elevated blood pressure"],
    },
    CatalogCode {
        code: "E11.9",
        code_type: CodeType::Icd10,
        description: "Type 2 diabetes mellitus without complications",
        category: "Endocrine, nutritional and metabolic diseases",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["E11.65", "E11.8"],
        keywords: &["diabetes", "type 2", "t2dm", "non-insulin dependent"],
    },
    CatalogCode {
        code: "R07.9",
        code_type: CodeType::Icd10,
        description: "Chest pain, unspecified",
        category: "Symptoms, signs and abnormal clinical and laboratory findings",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["R07.89", "R07.0"],
        keywords: &["chest pain", "thoracic pain", "precordial pain"],
    },
    CatalogCode {
        code: "R06.00",
        code_type: CodeType::Icd10,
        description: "Dyspnea, unspecified",
        category: "Symptoms, signs and abnormal clinical and laboratory findings",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["R06.02", "R06.09"],
        keywords: &[
            "dyspnea",
            "shortness of breath",
            "breathlessness",
            "difficulty breathing",
            "sob",
        ],
    },
    CatalogCode {
        code: "99213",
        code_type: CodeType::Cpt,
        description:
            "Office or other outpatient visit for the evaluation and management of an established patient",
        category: "Evaluation and Management",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["99212", "99214"],
        keywords: &[
            "office visit",
            "outpatient",
            "established patient",
            "evaluation",
            "management",
        ],
    },
    CatalogCode {
        code: "93000",
        code_type: CodeType::Cpt,
        description:
            "Electrocardiogram, routine ECG with at least 12 leads; with interpretation and report",
        category: "Medicine",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["93005", "93010"],
        keywords: &["ecg", "ekg", "electrocardiogram", "heart rhythm", "cardiac"],
    },
    CatalogCode {
        code: "36415",
        code_type: CodeType::Cpt,
        description: "Collection of venous blood by venipuncture",
        category: "Surgery",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["36416"],
        keywords: &["blood draw", "venipuncture", "phlebotomy", "blood collection"],
    },
    CatalogCode {
        code: "J45.909",
        code_type: CodeType::Icd10,
        description: "Unspecified asthma, uncomplicated",
        category: "Diseases of the respiratory system",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["J45.901", "J45.20"],
        keywords: &["asthma", "bronchial asthma", "reactive airway"],
    },
    CatalogCode {
        code: "J18.9",
        code_type: CodeType::Icd10,
        description: "Pneumonia, unspecified organism",
        category: "Diseases of the respiratory system",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["J15.9", "J18.1"],
        keywords: &["pneumonia", "lung infection", "pulmonary infection"],
    },
    CatalogCode {
        code: "J44.1",
        code_type: CodeType::Icd10,
        description: "Chronic obstructive pulmonary disease with acute exacerbation",
        category: "Diseases of the respiratory system",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["J44.0", "J44.9"],
        keywords: &[
            "copd",
            "chronic obstructive pulmonary disease",
            "emphysema",
            "chronic bronchitis",
        ],
    },
    CatalogCode {
        code: "I50.9",
        code_type: CodeType::Icd10,
        description: "Heart failure, unspecified",
        category: "Diseases of the circulatory system",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["I50.20", "I50.1"],
        keywords: &["heart failure", "congestive heart failure", "chf", "cardiac failure"],
    },
    CatalogCode {
        code: "I63.9",
        code_type: CodeType::Icd10,
        description: "Cerebral infarction, unspecified",
        category: "Diseases of the circulatory system",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["I64", "I63.5"],
        keywords: &["stroke", "cerebrovascular accident", "cva", "brain attack"],
    },
    CatalogCode {
        code: "R50.9",
        code_type: CodeType::Icd10,
        description: "Fever, unspecified",
        category: "Symptoms, signs and abnormal clinical and laboratory findings",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["R50.81", "R50.83"],
        keywords: &["fever", "pyrexia", "febrile", "elevated temperature"],
    },
    CatalogCode {
        code: "R51.9",
        code_type: CodeType::Icd10,
        description: "Headache, unspecified",
        category: "Symptoms, signs and abnormal clinical and laboratory findings",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["R51.0", "G43.909"],
        keywords: &["headache", "cephalgia", "head pain"],
    },
    CatalogCode {
        code: "R11.0",
        code_type: CodeType::Icd10,
        description: "Nausea",
        category: "Symptoms, signs and abnormal clinical and laboratory findings",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["R11.10", "R11.2"],
        keywords: &["nausea", "queasiness", "sickness"],
    },
    CatalogCode {
        code: "R53.83",
        code_type: CodeType::Icd10,
        description: "Other fatigue",
        category: "Symptoms, signs and abnormal clinical and laboratory findings",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["R53.1", "R53.81"],
        keywords: &["fatigue", "tiredness", "exhaustion", "weakness"],
    },
    CatalogCode {
        code: "R42",
        code_type: CodeType::Icd10,
        description: "Dizziness and giddiness",
        category: "Symptoms, signs and abnormal clinical and laboratory findings",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["H81.10"],
        keywords: &["dizziness", "lightheadedness", "vertigo"],
    },
    CatalogCode {
        code: "E66.9",
        code_type: CodeType::Icd10,
        description: "Obesity, unspecified",
        category: "Endocrine, nutritional and metabolic diseases",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["E66.01", "E66.8"],
        keywords: &["obesity", "overweight"],
    },
    CatalogCode {
        code: "D64.9",
        code_type: CodeType::Icd10,
        description: "Anemia, unspecified",
        category: "Diseases of the blood and blood-forming organs",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["D50.9", "D64.81"],
        keywords: &["anemia", "low hemoglobin"],
    },
    CatalogCode {
        code: "B99.9",
        code_type: CodeType::Icd10,
        description: "Unspecified infectious disease",
        category: "Certain infectious and parasitic diseases",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["B99", "A41.9"],
        keywords: &["infection", "infectious disease"],
    },
    CatalogCode {
        code: "Z88.0",
        code_type: CodeType::Icd10,
        description: "Allergy status to penicillin",
        category: "Factors influencing health status and contact with health services",
        is_billable: false,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["Z88.1", "Z88.8"],
        keywords: &["penicillin allergy", "pcn allergy"],
    },
    CatalogCode {
        code: "Z95.0",
        code_type: CodeType::Icd10,
        description: "Presence of cardiac pacemaker",
        category: "Factors influencing health status and contact with health services",
        is_billable: false,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["Z95.1", "Z95.8"],
        keywords: &["pacemaker", "cardiac pacemaker"],
    },
    CatalogCode {
        code: "Z99.11",
        code_type: CodeType::Icd10,
        description: "Dependence on respirator",
        category: "Factors influencing health status and contact with health services",
        is_billable: false,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["Z99.12", "Z99.81"],
        keywords: &["ventilator", "mechanical ventilator", "respirator"],
    },
    CatalogCode {
        code: "71046",
        code_type: CodeType::Cpt,
        description: "Radiologic examination, chest; 2 views",
        category: "Radiology",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["71045", "71047"],
        keywords: &["chest x-ray", "cxr", "radiograph"],
    },
    CatalogCode {
        code: "73030",
        code_type: CodeType::Cpt,
        description: "Radiologic examination, shoulder; 1 view",
        category: "Radiology",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["73020", "73040"],
        keywords: &["shoulder x-ray", "shoulder radiograph"],
    },
    CatalogCode {
        code: "70553",
        code_type: CodeType::Cpt,
        description:
            "Magnetic resonance imaging, brain; without contrast, followed by with contrast",
        category: "Radiology",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["70551", "70552"],
        keywords: &["mri brain", "magnetic resonance imaging"],
    },
    CatalogCode {
        code: "72148",
        code_type: CodeType::Cpt,
        description: "Magnetic resonance imaging, lumbar spine; without contrast",
        category: "Radiology",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["72149", "72158"],
        keywords: &["mri spine", "lumbar mri"],
    },
    CatalogCode {
        code: "71260",
        code_type: CodeType::Cpt,
        description: "Computed tomography, thorax; with contrast",
        category: "Radiology",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["71250", "71270"],
        keywords: &["ct chest", "computed tomography", "cat scan"],
    },
    CatalogCode {
        code: "74178",
        code_type: CodeType::Cpt,
        description: "Computed tomography, abdomen and pelvis; with contrast",
        category: "Radiology",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["74176", "74177"],
        keywords: &["ct abdomen", "ct pelvis", "abdominal ct"],
    },
    CatalogCode {
        code: "82947",
        code_type: CodeType::Cpt,
        description: "Glucose; quantitative, blood (except reagent strip)",
        category: "Pathology and Laboratory",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["82948", "82950"],
        keywords: &["glucose test", "blood sugar", "fasting glucose"],
    },
    CatalogCode {
        code: "80061",
        code_type: CodeType::Cpt,
        description: "Lipid panel",
        category: "Pathology and Laboratory",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["80076", "83718"],
        keywords: &["cholesterol test", "lipid panel", "lipid profile"],
    },
    CatalogCode {
        code: "83036",
        code_type: CodeType::Cpt,
        description: "Hemoglobin; glycosylated (A1C)",
        category: "Pathology and Laboratory",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["83037", "83038"],
        keywords: &["hemoglobin a1c", "hba1c", "a1c", "glycated hemoglobin"],
    },
    CatalogCode {
        code: "94760",
        code_type: CodeType::Cpt,
        description: "Noninvasive ear or pulse oximetry for oxygen saturation",
        category: "Medicine",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["94761", "94762"],
        keywords: &["oxygen saturation", "spo2", "pulse oximetry"],
    },
    CatalogCode {
        code: "33208",
        code_type: CodeType::Cpt,
        description: "Insertion of pacemaker, single chamber",
        category: "Surgery",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["33206", "33210"],
        keywords: &["pacemaker", "cardiac pacemaker"],
    },
    CatalogCode {
        code: "94002",
        code_type: CodeType::Cpt,
        description:
            "Ventilation assist and management, initiation of pressure or volume preset ventilator assistance",
        category: "Medicine",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["94003", "94004"],
        keywords: &["ventilator", "mechanical ventilator", "respirator"],
    },
    CatalogCode {
        code: "85025",
        code_type: CodeType::Cpt,
        description: "Blood count; complete (CBC), automated",
        category: "Pathology and Laboratory",
        is_billable: true,
        effective_date: 0,
        expiration_date: None,
        related_codes: &["85027", "85048"],
        keywords: &["blood count", "cbc", "complete blood count"],
    },
];
