#!/usr/bin/env bash
#
# Tests for scripts/check_onramp_ownership.py (Issue #1652).
#
# Self-contained: builds a sandbox with a synthetic Cargo.toml, two contract
# directories and one non-existent path, so it needs no cargo build and runs in
# seconds.
#
# Usage: bash tests/onramp_ownership_test.sh
#
set -uo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GATE="$ROOT_DIR/scripts/check_onramp_ownership.py"

PASS=0
FAIL=0

ok()   { echo "  ok   - $1"; PASS=$((PASS + 1)); }
nope() { echo "  FAIL - $1"; FAIL=$((FAIL + 1)); }

expect_exit() {
  local want="$1" got="$2" what="$3"
  if [[ "$got" -eq "$want" ]]; then ok "$what (exit $got)"; else nope "$what (want exit $want, got $got)"; fi
}

expect_contains() {
  local file="$1" needle="$2" what="$3"
  if grep -qF -- "$needle" "$file"; then ok "$what"; else nope "$what (missing: $needle)"; fi
}

# A sandbox whose manifest excludes two real crates and one missing path.
setup() {
  SANDBOX="$(mktemp -d)"
  mkdir -p "$SANDBOX/contracts/foo" "$SANDBOX/contracts/bar" "$SANDBOX/docs"
  cat > "$SANDBOX/Cargo.toml" <<'EOF'
[workspace]
exclude = [
    "contracts/foo",
    "contracts/bar",
    "contracts/gone",
]
EOF
  printf 'soroban-sdk = { workspace = true }\n' > "$SANDBOX/contracts/foo/Cargo.toml"
  printf 'soroban-sdk = "21.7.7"\n' > "$SANDBOX/contracts/bar/Cargo.toml"
  cat > "$SANDBOX/docs/ONRAMP_OWNERSHIP.md" <<'EOF'
# On-Ramp Ownership

<!-- BEGIN: onramp-ownership (generated by scripts/check_onramp_ownership.py; run with --write) -->
| Excluded path | Contract | Owner | Assignee | Blocker | Status | Target | Last reviewed |
| --- | --- | --- | --- | --- | --- | --- | --- |
<!-- END: onramp-ownership -->
EOF
}

teardown() { [[ -n "${SANDBOX:-}" ]] && rm -rf "$SANDBOX"; }

run_gate() {
  python3 "$GATE" --root "$SANDBOX" >"$SANDBOX/out.txt" 2>&1
}

# ── 0. The real repository passes as-is ────────────────────────────────────
echo "live repository"
python3 "$GATE" --root "$ROOT_DIR" >/tmp/onramp_live.txt 2>&1
expect_exit 0 $? "the committed ownership map matches Cargo.toml"
rm -f /tmp/onramp_live.txt

# ── 1. --write generates a complete, valid map ─────────────────────────────
echo "generate"
setup
python3 "$GATE" --root "$SANDBOX" --write >"$SANDBOX/write.txt" 2>&1
expect_exit 0 $? "--write succeeds on an empty table"
expect_contains "$SANDBOX/write.txt" "3 excluded paths" "reports how many paths it wrote"
expect_contains "$SANDBOX/docs/ONRAMP_OWNERSHIP.md" 'contracts/gone' "adds a row for a missing path"
expect_contains "$SANDBOX/docs/ONRAMP_OWNERSHIP.md" 'stale-entry' "classifies a missing path as stale-entry"
run_gate
expect_exit 0 $? "the generated map passes the check"
teardown

# ── 2. Missing row (path reintegrated but map stale) ───────────────────────
echo "missing row"
setup
python3 "$GATE" --root "$SANDBOX" --write >/dev/null 2>&1
sed -i '/contracts\/bar/d' "$SANDBOX/docs/ONRAMP_OWNERSHIP.md"
run_gate
expect_exit 1 $? "a path missing from the map fails"
expect_contains "$SANDBOX/out.txt" "missing from the map" "names the missing path problem"
teardown

# ── 3. Extra row (map lists a path no longer excluded) ─────────────────────
echo "extra row"
setup
python3 "$GATE" --root "$SANDBOX" --write >/dev/null 2>&1
sed -i '/<!-- END: onramp-ownership -->/i | `contracts/extra` | `extra` | @owner | unassigned | none | deferred | #828 on-ramp | 2026-09-30 |' \
  "$SANDBOX/docs/ONRAMP_OWNERSHIP.md"
run_gate
expect_exit 1 $? "a path no longer excluded fails"
expect_contains "$SANDBOX/out.txt" "not excluded in Cargo.toml" "names the extra path problem"
teardown

# ── 4. in-progress requires a named assignee ───────────────────────────────
echo "assignee required"
setup
python3 "$GATE" --root "$SANDBOX" --write >/dev/null 2>&1
sed -i 's/| deferred |/| in-progress |/' "$SANDBOX/docs/ONRAMP_OWNERSHIP.md"
run_gate
expect_exit 1 $? "in-progress with unassigned fails"
expect_contains "$SANDBOX/out.txt" "requires a named assignee" "explains the assignee requirement"
teardown

# ── 5. Status must agree with the filesystem ───────────────────────────────
echo "status consistency"
setup
python3 "$GATE" --root "$SANDBOX" --write >/dev/null 2>&1
sed -i 's/| stale-entry |/| deferred |/' "$SANDBOX/docs/ONRAMP_OWNERSHIP.md"
run_gate
expect_exit 1 $? "a missing path not marked stale-entry fails"
expect_contains "$SANDBOX/out.txt" "must be 'stale-entry'" "explains the stale-entry requirement"
teardown

# ── 6. A real crate cannot be not-a-crate ──────────────────────────────────
echo "crate status"
setup
python3 "$GATE" --root "$SANDBOX" --write >/dev/null 2>&1
sed -i 's/| deferred |/| not-a-crate |/' "$SANDBOX/docs/ONRAMP_OWNERSHIP.md"
run_gate
expect_exit 1 $? "a path with a Cargo.toml cannot be not-a-crate"
expect_contains "$SANDBOX/out.txt" "cannot be 'not-a-crate'" "explains the Cargo.toml requirement"
teardown

# ── 7. Duplicate rows fail ─────────────────────────────────────────────────
echo "duplicate rows"
setup
python3 "$GATE" --root "$SANDBOX" --write >/dev/null 2>&1
awk '/contracts\/foo/ {print; print; next} {print}' \
  "$SANDBOX/docs/ONRAMP_OWNERSHIP.md" > "$SANDBOX/doc.tmp" && mv "$SANDBOX/doc.tmp" "$SANDBOX/docs/ONRAMP_OWNERSHIP.md"
run_gate
expect_exit 1 $? "a duplicated path fails"
expect_contains "$SANDBOX/out.txt" "more than once" "names the duplicate problem"
teardown

echo
echo "passed: $PASS, failed: $FAIL"
[[ "$FAIL" -eq 0 ]]
