#!/usr/bin/env python3
"""Fail if docs/SYSTEM_ARCHITECTURE.md disagrees with the root Cargo.toml exclude list.

Issue #1603. The architecture doc used to carry a hand-maintained
"Excluded Contracts Audit" table. Every PR that touched an excluded contract
appended a row to it, and because each row recorded the state of the world at
the time it was written, the table ended up describing 24 different snapshots
at once and contradicting both Cargo.toml and itself:

  * `aml` and `rbac` are in Cargo.toml `exclude` but appear in a row labelled
    "Fix & Include (reintegrated at HEAD) ... Compile clean".
  * The dedicated `explainable_ai`/`sut_token` section states that "sut_token
    remains in the exclude list by design". It is not in the exclude list.
  * Several rows say a contract is "Tracked in `Cargo.toml` `exclude` block"
    when it is not excluded there.

Rather than reconcile 24 contradictory rows by hand, the table is now generated
from the manifest and this check keeps the two in step. The per-contract
rationale lives in Cargo.toml comments and issue #828, where it belongs; the doc
keeps the policy and the generated list.

Usage:
    python3 scripts/check_architecture_doc_drift.py            # check (CI)
    python3 scripts/check_architecture_doc_drift.py --write    # regenerate

Exits 0 when the doc matches Cargo.toml, 1 otherwise.
"""

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST = REPO_ROOT / "Cargo.toml"
DOC = REPO_ROOT / "docs" / "SYSTEM_ARCHITECTURE.md"

BEGIN_MARKER = (
    "<!-- BEGIN: excluded-contracts "
    "(generated by scripts/check_architecture_doc_drift.py; run with --write) -->"
)
END_MARKER = "<!-- END: excluded-contracts -->"


def parse_exclude(manifest_text):
    """Return the excluded paths from the root manifest, in declaration order.

    Deliberately not a full TOML parse: the exclude block is a flat list of
    string literals and this keeps the check dependency-free.
    """
    match = re.search(
        r"^exclude\s*=\s*\[(.*?)\]", manifest_text, re.S | re.M
    )
    if not match:
        raise SystemExit(
            "[arch-doc] could not find an `exclude = [...]` list in Cargo.toml"
        )
    return re.findall(r'"([^"]+)"', match.group(1))


def split_block(doc_text):
    """Return (before, generated_block, after) or raise if the markers are missing."""
    start = doc_text.find(BEGIN_MARKER)
    end = doc_text.find(END_MARKER)
    if start == -1 or end == -1 or end < start:
        raise SystemExit(
            "[arch-doc] docs/SYSTEM_ARCHITECTURE.md is missing the generated "
            "excluded-contracts block.\n"
            f"           expected markers:\n"
            f"             {BEGIN_MARKER}\n"
            f"             {END_MARKER}\n"
            "           recreate it with --write"
        )
    return (
        doc_text[:start],
        doc_text[start + len(BEGIN_MARKER) : end],
        doc_text[end + len(END_MARKER) :],
    )


def paths_in_block(block):
    """Excluded paths listed in the generated block, in document order.

    Reads the first column, which holds the full `contracts/<name>` path.
    """
    return re.findall(r"^\|\s*`([^`]+)`\s*\|", block, re.M)


def render(paths):
    """Build the generated block body from the manifest."""
    lines = [
        "",
        "| Excluded path | Contract | `Cargo.toml` present |",
        "| --- | --- | --- |",
    ]
    for path in paths:
        name = path.split("/")[-1]
        manifest = "yes" if (REPO_ROOT / path / "Cargo.toml").is_file() else "**no**"
        lines.append(f"| `{path}` | `{name}` | {manifest} |")
    lines.append("")
    lines.append(
        f"{len(paths)} paths, taken verbatim from the root `Cargo.toml` `exclude` "
        "list. Regenerate with "
        "`python3 scripts/check_architecture_doc_drift.py --write`."
    )
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write",
        action="store_true",
        help="rewrite the generated block in the doc to match Cargo.toml",
    )
    args = parser.parse_args()

    if not MANIFEST.is_file():
        raise SystemExit(f"[arch-doc] missing {MANIFEST}")
    if not DOC.is_file():
        raise SystemExit(f"[arch-doc] missing {DOC}")

    paths = parse_exclude(MANIFEST.read_text())
    if not paths:
        raise SystemExit("[arch-doc] Cargo.toml excludes nothing; refusing to continue")

    doc_text = DOC.read_text()
    before, block, after = split_block(doc_text)
    rendered = render(paths)
    expected_block = BEGIN_MARKER + rendered + END_MARKER

    if args.write:
        # Compare the block body only; `block` excludes the markers.
        if block.strip() == rendered.strip():
            print(f"[arch-doc] already up to date ({len(paths)} excluded paths).")
            return 0
        DOC.write_text(before + expected_block + after)
        print(
            f"[arch-doc] rewrote the excluded-contracts block in "
            f"{DOC.relative_to(REPO_ROOT)} ({len(paths)} excluded paths)."
        )
        return 0

    problems = []

    documented = paths_in_block(block)

    missing = [p for p in paths if p not in documented]
    if missing:
        problems.append(
            "excluded in Cargo.toml but absent from the doc table: "
            + ", ".join(missing)
        )

    extra = [p for p in documented if p not in paths]
    if extra:
        problems.append(
            "listed in the doc table but not excluded in Cargo.toml: "
            + ", ".join(extra)
        )

    duplicated = sorted({p for p in documented if documented.count(p) > 1})
    if duplicated:
        problems.append("listed more than once in the doc table: " + ", ".join(duplicated))

    if documented != paths:
        order_note = ""
        if not missing and not extra and not duplicated:
            order_note = " (same contents, different order; regenerate with --write)"
        problems.append("the doc table does not match the manifest order" + order_note)

    absent_on_disk = [p for p in paths if not (REPO_ROOT / p).is_dir()]
    if absent_on_disk:
        problems.append(
            "excluded in Cargo.toml but the path does not exist: "
            + ", ".join(absent_on_disk)
        )

    if problems:
        print(
            "[arch-doc] docs/SYSTEM_ARCHITECTURE.md is out of step with "
            "Cargo.toml:",
            file=sys.stderr,
        )
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        print(
            "\n  Regenerate with: "
            "python3 scripts/check_architecture_doc_drift.py --write",
            file=sys.stderr,
        )
        return 1

    print(
        f"[arch-doc] docs/SYSTEM_ARCHITECTURE.md matches Cargo.toml "
        f"({len(paths)} excluded paths)."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
