#!/usr/bin/env python3
"""Keep the excluded-contract ownership map in step with `Cargo.toml` (#1652).

`Cargo.toml` says which contracts are excluded from the workspace; it says
nothing about *who* is bringing each one back or what is stopping them. Without
that, the on-ramp backlog (issue #828) is a list of names with no accountable
owner, and progress is invisible.

`docs/ONRAMP_OWNERSHIP.md` is that map. Its table lists one row per excluded
path with an owner, an assignee, the current blocker, a progress status and the
last review date. This script is the contract between the map and the manifest:

* every `workspace.exclude` path has exactly one row, in manifest order;
* every row has non-empty owner / blocker / target fields and a valid status;
* status is consistent with the row (`in-progress` needs a named assignee; a
  path that no longer exists must be `stale-entry`; a path with no `Cargo.toml`
  must be `not-a-crate`).

Rather than reconcile a hand-edited table by eye, run `--write` to add rows for
newly excluded paths and drop rows for paths that have been reintegrated. It
preserves the owner/blocker/status of existing rows, so maintainer edits are
never clobbered.

Usage:
    python3 scripts/check_onramp_ownership.py            # check (CI)
    python3 scripts/check_onramp_ownership.py --write    # add/drop/reorder rows
    python3 scripts/check_onramp_ownership.py --json

Exits 0 when the map is complete and consistent, 1 otherwise.
"""

import argparse
import datetime
import json
import re
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST = REPO_ROOT / "Cargo.toml"
DOC = REPO_ROOT / "docs" / "ONRAMP_OWNERSHIP.md"

BEGIN_MARKER = (
    "<!-- BEGIN: onramp-ownership "
    "(generated by scripts/check_onramp_ownership.py; run with --write) -->"
)
END_MARKER = "<!-- END: onramp-ownership -->"

COLUMNS = (
    "Excluded path",
    "Contract",
    "Owner",
    "Assignee",
    "Blocker",
    "Status",
    "Target",
    "Last reviewed",
)
HEADER = "| " + " | ".join(COLUMNS) + " |"
SEPARATOR = "| " + " | ".join("---" for _ in COLUMNS) + " |"

# Progress vocabulary. `deferred` and `blocked` are distinguishable on purpose:
# the first is "known, not scheduled", the second is "someone looked and hit a
# wall". `in-progress` and `reintegration-ready` are the only states that
# require a named assignee.
STATUSES = (
    "not-started",
    "deferred",
    "blocked",
    "in-progress",
    "reintegration-ready",
    "not-a-crate",
    "stale-entry",
)
NEEDS_ASSIGNEE = {"in-progress", "reintegration-ready"}
DEFAULT_OWNER = "@Stellar-Uzima/maintainers"
UNASSIGNED = "unassigned"


def load_excluded_paths():
    """Return `workspace.exclude` from the root manifest, in declaration order."""
    try:
        manifest = tomllib.loads(MANIFEST.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as error:
        raise SystemExit(f"[onramp] cannot parse {MANIFEST.name}: {error}") from error
    paths = manifest.get("workspace", {}).get("exclude")
    if not isinstance(paths, list) or not paths:
        raise SystemExit("[onramp] Cargo.toml has no workspace.exclude list")
    return paths


def split_block(text):
    start = text.find(BEGIN_MARKER)
    end = text.find(END_MARKER)
    if start == -1 or end == -1 or end < start:
        raise SystemExit(
            "[onramp] docs/ONRAMP_OWNERSHIP.md is missing the generated "
            "ownership block.\n"
            f"         expected markers:\n"
            f"           {BEGIN_MARKER}\n"
            f"           {END_MARKER}\n"
            "         recreate it with --write"
        )
    return text[:start], text[start + len(BEGIN_MARKER) : end], text[end + len(END_MARKER) :]


def parse_rows(block):
    """Return the table rows as dicts; prose lines around the table are ignored."""
    lines = [line.strip() for line in block.splitlines() if line.strip().startswith("|")]
    header = lines[0] if lines else None
    if header != HEADER:
        raise SystemExit(
            "[onramp] the ownership table header changed.\n"
            f"         expected: {HEADER}\n"
            f"         found:    {header}\n"
            "         restore it with --write"
        )
    rows = []
    for line in lines[2:]:  # skip header + separator
        cells = [cell.strip() for cell in line.strip().strip("|").split("|")]
        if len(cells) != len(COLUMNS):
            raise SystemExit(
                f"[onramp] row has {len(cells)} columns, expected {len(COLUMNS)}: {line}"
            )
        path_cell = cells[0]
        match = re.match(r"^`([^`]+)`$", path_cell)
        if not match:
            raise SystemExit(f"[onramp] first column must be a `path`: {line}")
        row = dict(zip(COLUMNS, cells))
        row["Excluded path"] = match.group(1)
        rows.append(row)
    return rows


def defaults_for(path):
    """Seed a row for `path` from the manifest and the filesystem."""
    directory = REPO_ROOT / path
    name = path.split("/")[-1]
    if not directory.is_dir():
        return {
            "Excluded path": path,
            "Contract": f"`{name}`",
            "Owner": DEFAULT_OWNER,
            "Assignee": UNASSIGNED,
            "Blocker": "path no longer exists; remove it from Cargo.toml `exclude`",
            "Status": "stale-entry",
            "Target": "#828 on-ramp",
            "Last reviewed": datetime.date.today().isoformat(),
        }
    manifest = directory / "Cargo.toml"
    if not manifest.is_file():
        return {
            "Excluded path": path,
            "Contract": f"`{name}`",
            "Owner": DEFAULT_OWNER,
            "Assignee": UNASSIGNED,
            "Blocker": "directory is not a crate root (no Cargo.toml); cannot be a workspace member",
            "Status": "not-a-crate",
            "Target": "#828 on-ramp",
            "Last reviewed": datetime.date.today().isoformat(),
        }
    try:
        inherits = "{ workspace = true" in manifest.read_text(encoding="utf-8")
    except OSError:
        inherits = False
    blocker = (
        "`soroban-sdk = { workspace = true }` cannot resolve while the crate is "
        "excluded from the workspace"
        if inherits
        else "triaged under issue #828; see the Cargo.toml comment for this entry"
    )
    return {
        "Excluded path": path,
        "Contract": f"`{name}`",
        "Owner": DEFAULT_OWNER,
        "Assignee": UNASSIGNED,
        "Blocker": blocker,
        "Status": "deferred",
        "Target": "#828 on-ramp",
        "Last reviewed": datetime.date.today().isoformat(),
    }


def render(rows):
    lines = ["", HEADER, SEPARATOR]
    for row in rows:
        cells = []
        for column in COLUMNS:
            value = str(row[column]).replace("\n", " ")
            if column == "Excluded path":
                value = f"`{value}`"
            cells.append(value)
        lines.append("| " + " | ".join(cells) + " |")
    lines.append("")
    lines.append(
        "Every row above is one entry from the root `Cargo.toml` `workspace.exclude` "
        "list. Regenerate with `python3 scripts/check_onramp_ownership.py --write`."
    )
    lines.append("")
    return "\n".join(lines)


def validate(rows, manifest_paths):
    problems = []

    documented = [row["Excluded path"] for row in rows]
    for path in manifest_paths:
        if path not in documented:
            problems.append(f"excluded in Cargo.toml but missing from the map: {path}")
    for path in documented:
        if path not in manifest_paths:
            problems.append(f"listed in the map but not excluded in Cargo.toml: {path}")
    duplicates = sorted({p for p in documented if documented.count(p) > 1})
    if duplicates:
        problems.append("listed more than once in the map: " + ", ".join(duplicates))
    if documented != manifest_paths:
        note = "" if (problems and (set(documented) != set(manifest_paths))) else \
            " (same contents, different order; regenerate with --write)"
        problems.append("the map does not match the manifest order" + note)

    for row in rows:
        path = row["Excluded path"]
        for column in ("Contract", "Owner", "Assignee", "Blocker", "Status", "Target", "Last reviewed"):
            if not row[column]:
                problems.append(f"{path}: empty `{column}`")
        if "|" in row["Blocker"]:
            problems.append(f"{path}: `Blocker` must not contain a pipe character")
        status = row["Status"]
        if status not in STATUSES:
            problems.append(
                f"{path}: status '{status}' is not one of " + ", ".join(STATUSES)
            )
            continue
        assignee = row["Assignee"]
        if status in NEEDS_ASSIGNEE and assignee == UNASSIGNED:
            problems.append(f"{path}: status '{status}' requires a named assignee")
        if assignee not in (UNASSIGNED, "") and not assignee.startswith("@"):
            problems.append(f"{path}: assignee '{assignee}' must start with '@' or be 'unassigned'")
        try:
            datetime.date.fromisoformat(row["Last reviewed"])
        except ValueError:
            problems.append(f"{path}: 'Last reviewed' is not YYYY-MM-DD: {row['Last reviewed']}")

        exists = (REPO_ROOT / path).is_dir()
        has_manifest = (REPO_ROOT / path / "Cargo.toml").is_file()
        if not exists and status != "stale-entry":
            problems.append(
                f"{path}: path does not exist, so status must be 'stale-entry' (is '{status}')"
            )
        if exists and status == "stale-entry":
            problems.append(f"{path}: status 'stale-entry' but the path exists on disk")
        if exists and has_manifest and status == "not-a-crate":
            problems.append(
                f"{path}: has a Cargo.toml, so status cannot be 'not-a-crate'"
            )
        if exists and not has_manifest and status not in ("not-a-crate", "stale-entry"):
            problems.append(
                f"{path}: no Cargo.toml, so status must be 'not-a-crate' (is '{status}')"
            )
    return problems


def merge(existing_rows, manifest_paths):
    """Rows for the manifest, in manifest order, preserving existing fields."""
    by_path = {row["Excluded path"]: row for row in existing_rows}
    merged = []
    for path in manifest_paths:
        row = by_path.get(path)
        if row is None:
            merged.append(defaults_for(path))
        else:
            row["Contract"] = f"`{path.split('/')[-1]}`"
            merged.append(row)
    return merged


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=None, help="repository root (default: repo)")
    parser.add_argument("--write", action="store_true", help="rewrite the ownership table")
    parser.add_argument("--json", action="store_true", help="machine-readable output")
    args = parser.parse_args()

    if args.root:
        global REPO_ROOT, MANIFEST, DOC
        REPO_ROOT = Path(args.root).resolve()
        MANIFEST = REPO_ROOT / "Cargo.toml"
        DOC = REPO_ROOT / "docs" / "ONRAMP_OWNERSHIP.md"

    if not MANIFEST.is_file():
        raise SystemExit(f"[onramp] missing {MANIFEST}")
    if not DOC.is_file():
        raise SystemExit(f"[onramp] missing {DOC}")

    manifest_paths = load_excluded_paths()
    doc_text = DOC.read_text(encoding="utf-8")
    before, block, after = split_block(doc_text)
    rows = parse_rows(block)

    if args.write:
        merged = merge(rows, manifest_paths)
        rendered = render(merged)
        if rendered.strip() == block.strip():
            print("[onramp] ownership map already up to date "
                  f"({len(manifest_paths)} excluded paths).")
            return 0
        DOC.write_text(before + BEGIN_MARKER + rendered + END_MARKER + after)
        print(
            f"[onramp] rewrote the ownership map in {DOC.relative_to(REPO_ROOT)} "
            f"({len(manifest_paths)} excluded paths)."
        )
        return 0

    problems = validate(rows, manifest_paths)
    counts = {}
    for row in rows:
        counts[row["Status"]] = counts.get(row["Status"], 0) + 1

    if args.json:
        print(json.dumps({"paths": len(manifest_paths), "status_counts": counts,
                          "problems": problems}, indent=2))
    else:
        print(
            f"[onramp] {len(rows)} row(s) for {len(manifest_paths)} excluded "
            "path(s); status: "
            + ", ".join(f"{status}={count}" for status, count in sorted(counts.items()))
        )
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)

    if problems:
        print(
            "\n  Regenerate with: "
            "python3 scripts/check_onramp_ownership.py --write",
            file=sys.stderr,
        )
        return 1

    if not args.json:
        print("[onramp] ownership map matches Cargo.toml.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
