#!/usr/bin/env bash
# manage_secrets.sh - Per-network secrets and identity management tooling
# with safe defaults for Stellar Soroban deployments.
#
# Usage:
#   ./scripts/manage_secrets.sh <command> [options]
#
# Commands:
#   init        Initialize secrets structure for a network
#   generate    Generate a new identity/secret for a network
#   list        List configured secrets and identities
#   rotate      Rotate an existing secret or identity
#   validate    Validate secrets configuration against schema
#   export      Export secrets for a specific network (env-safe format)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_DIR="$ROOT_DIR/config"
SECRETS_DIR="$ROOT_DIR/.secrets"
NETWORKS_CONFIG="$CONFIG_DIR/networks.toml"

# Source logger
source "$SCRIPT_DIR/logger.sh"

# ─── Constants ───────────────────────────────────────────────────────────────

SUPPORTED_NETWORKS=("local" "testnet" "futurenet" "mainnet")

DEFAULT_IDENTITY_NAMES=("admin" "deployer" "approver")
DEFAULT_COOLDOWN_SECONDS=86400
DEFAULT_RATE_LIMIT_MAX_REQUESTS=5
DEFAULT_RATE_LIMIT_WINDOW_SECONDS=3600
DEFAULT_MFA_THRESHOLD=2
DEFAULT_SESSION_TTL_SECONDS=3600

# ─── Helpers ─────────────────────────────────────────────────────────────────

usage() {
    cat <<EOF
Usage: $(basename "$0") <command> [options]

Commands:
  init <network>               Initialize secrets structure for <network>
  generate <network> <name>    Generate a new identity/secret
  list <network>               List configured secrets and identities
  rotate <network> <name>      Rotate an existing secret or identity
  validate <network>           Validate secrets configuration
  export <network>             Export secrets in env-safe format

Options:
  --identity-type <type>       Identity type: deployer, admin, approver (default: deployer)
  --key-type <type>            Key type: ed25519, sr25519 (default: ed25519)
  --force                     Overwrite existing secrets
  --dry-run                   Show what would be done without executing
  -h, --help                  Show this help message

Supported networks: ${SUPPORTED_NETWORKS[*]}
EOF
}

validate_network() {
    local network="$1"
    for n in "${SUPPORTED_NETWORKS[@]}"; do
        if [[ "$n" == "$network" ]]; then
            return 0
        fi
    done
    log "ERROR" "Unknown network: $network. Supported: ${SUPPORTED_NETWORKS[*]}"
    exit 1
}

require_networks_config() {
    if [[ ! -f "$NETWORKS_CONFIG" ]]; then
        log "ERROR" "Networks config not found: $NETWORKS_CONFIG"
        exit 1
    fi
}

get_network_config() {
    local network="$1"
    local key="$2"
    awk -F'=' -v section="[networks.$network]" -v key="$key" '
        /^\[.*\] { current = $0 }
        current == section && $1 == key { gsub(/^[[:space:]]+|[[:space:]]+$/, "", $2); gsub(/"/, "", $2); print $2 }
    ' "$NETWORKS_CONFIG"
}

# ─── Commands ────────────────────────────────────────────────────────────────

cmd_init() {
    local network="$1"
    local force="${2:-false}"

    validate_network "$network"
    require_networks_config

    local network_dir="$SECRETS_DIR/$network"
    local identity_dir="$network_dir/identities"
    local keys_dir="$network_dir/keys"

    if [[ -d "$network_dir" && "$force" != "true" ]]; then
        log "WARN" "Secrets directory for '$network' already exists. Use --force to overwrite."
        return 0
    fi

    log "INFO" "Initializing secrets structure for network: $network"

    mkdir -p "$identity_dir" "$keys_dir"

    cat > "$network_dir/config.toml" <<EOFCFG
# Secrets configuration for network: $network
# Generated by manage_secrets.sh

[network]
name = "$network"
rpc-url = "$(get_network_config "$network" "rpc-url")"
network-passphrase = "$(get_network_config "$network" "network-passphrase")"

[secrets]
encryption_enabled = false
rotation_policy_days = 30
max_secret_age_days = 90

[identity]
default_type = "deployer"
key_type = "ed25519"

[rate_limit]
max_requests_per_window = $DEFAULT_RATE_LIMIT_MAX_REQUESTS
window_seconds = $DEFAULT_RATE_LIMIT_WINDOW_SECONDS
cooldown_seconds = $DEFAULT_COOLDOWN_SECONDS

[session]
ttl_seconds = $DEFAULT_SESSION_TTL_SECONDS
mfa_threshold = $DEFAULT_MFA_THRESHOLD
EOFCFG

    cat > "$network_dir/.gitignore" <<EOFGIT
# Never commit actual secrets
*.key
*.pem
*.secret
*.env
*.env.local
# Keep tracked
config.toml
.gitignore
EOFGIT

    for name in "${DEFAULT_IDENTITY_NAMES[@]}"; do
        generate_identity "$network" "$name" "ed25519" "false"
    done

    log "INFO" "Secrets structure initialized for '$network' at: $network_dir"
}

generate_identity() {
    local network="$1"
    local name="$2"
    local key_type="${3:-ed25519}"
    local is_call="${4:-true}"

    if [[ "$is_call" == "true" ]]; then
        validate_network "$network"
    fi

    local identity_dir="$SECRETS_DIR/$network/identities/$name"

    if [[ -d "$identity_dir" ]]; then
        log "WARN" "Identity '$name' already exists for network '$network'. Skipping."
        return 0
    fi

    mkdir -p "$identity_dir"

    if command -v soroban &>/dev/null; then
        log "INFO" "Generating Soroban identity: $name (network: $network)"
        local address
        address=$(soroban config identity generate "$name" 2>/dev/null || echo "pending-generation")
        echo "$address" > "$identity_dir/address.txt"
    elif command -v openssl &>/dev/null; then
        log "INFO" "Generating ed25519 keypair for identity: $name"
        openssl genpkey -algorithm ed25519 -out "$identity_dir/$name.key" 2>/dev/null
        openssl pkey -in "$identity_dir/$name.key" -pubout -out "$identity_dir/$name.pub" 2>/dev/null
        echo "key-generated-$(date +%s)" > "$identity_dir/address.txt"
    else
        log "WARN" "Neither soroban nor openssl found. Creating placeholder identity."
        echo "placeholder-$(date +%s)" > "$identity_dir/address.txt"
    fi

    cat > "$identity_dir/metadata.toml" <<EOFMETA
# Identity metadata for: $name
[identity]
name = "$name"
network = "$network"
key_type = "$key_type"
created_at = "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
rotated_at = ""
rotation_count = 0
EOFMETA

    if [[ "$is_call" == "true" ]]; then
        log "INFO" "Identity '$name' generated for network '$network'"
    fi
}

cmd_generate() {
    local network="$1"
    local name="$2"
    local key_type="${3:-ed25519}"
    local force="${4:-false}"

    validate_network "$network"

    if [[ -z "$name" ]]; then
        log "ERROR" "Identity name is required"
        exit 1
    fi

    if [[ -d "$SECRETS_DIR/$network/identities/$name" && "$force" != "true" ]]; then
        log "ERROR" "Identity '$name' exists. Use --force to overwrite."
        exit 1
    fi

    generate_identity "$network" "$name" "$key_type" "true"
}

cmd_list() {
    local network="$1"

    validate_network "$network"

    local network_dir="$SECRETS_DIR/$network"

    if [[ ! -d "$network_dir" ]]; then
        log "WARN" "No secrets configured for network: $network"
        log "INFO" "Run: $(basename "$0") init $network"
        return 0
    fi

    echo "=== Secrets for network: $network ==="
    echo ""

    echo "Identities:"
    local identity_dir="$network_dir/identities"
    if [[ -d "$identity_dir" ]]; then
        for identity_path in "$identity_dir"/*/; do
            if [[ -d "$identity_path" ]]; then
                local identity_name
                identity_name=$(basename "$identity_path")
                local address=""
                if [[ -f "$identity_path/address.txt" ]]; then
                    address=$(cat "$identity_path/address.txt")
                fi
                printf "  %-20s %s\n" "$identity_name" "${address:-no-address}"
            fi
        done
    else
        echo "  (none)"
    fi

    echo ""

    if [[ -f "$network_dir/config.toml" ]]; then
        echo "Configuration:"
        grep -E '^(max_requests|window_seconds|cooldown_seconds|ttl_seconds|mfa_threshold)' "$network_dir/config.toml" 2>/dev/null | \
            while IFS='=' read -r key value; do
                printf "  %-30s %s\n" "$key" "$value"
            done
    fi
}

cmd_rotate() {
    local network="$1"
    local name="$2"

    validate_network "$network"

    local identity_dir="$SECRETS_DIR/$network/identities/$name"

    if [[ ! -d "$identity_dir" ]]; then
        log "ERROR" "Identity '$name' not found for network '$network'"
        exit 1
    fi

    log "INFO" "Rotating identity '$name' for network '$network'"

    local archive_dir="$identity_dir/archive"
    mkdir -p "$archive_dir"
    local timestamp
    timestamp=$(date -u +"%Y%m%dT%H%M%SZ")

    if [[ -f "$identity_dir/address.txt" ]]; then
        cp "$identity_dir/address.txt" "$archive_dir/address_${timestamp}.txt"
    fi

    generate_identity "$network" "$name" "ed25519" "true"

    if [[ -f "$identity_dir/metadata.toml" ]]; then
        sed -i "s/^rotated_at = .*/rotated_at = \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"/" "$identity_dir/metadata.toml" 2>/dev/null || true
    fi

    log "INFO" "Identity '$name' rotated successfully. Old keys archived to: $archive_dir"
}

cmd_validate() {
    local network="$1"

    validate_network "$network"
    require_networks_config

    local network_dir="$SECRETS_DIR/$network"
    local violations=0

    log "INFO" "Validating secrets configuration for network: $network"

    if [[ ! -d "$network_dir" ]]; then
        log "ERROR" "Secrets directory not found for network: $network"
        log "INFO" "Run: $(basename "$0") init $network"
        exit 1
    fi

    if [[ ! -f "$network_dir/config.toml" ]]; then
        log "ERROR" "Missing config.toml for network: $network"
        violations=$((violations + 1))
    fi

    for name in "${DEFAULT_IDENTITY_NAMES[@]}"; do
        if [[ ! -d "$network_dir/identities/$name" ]]; then
            log "ERROR" "Missing required identity: $name"
            violations=$((violations + 1))
        fi
    done

    local leaked
    leaked=$(find "$network_dir" -name "*.key" -o -name "*.pem" -o -name "*.secret" 2>/dev/null | wc -l)
    if (( leaked > 0 )); then
        log "WARN" "Found $leaked secret key files in tracked directory"
    fi

    if [[ ! -f "$network_dir/.gitignore" ]]; then
        log "WARN" "Missing .gitignore in secrets directory"
    fi

    if (( violations > 0 )); then
        log "ERROR" "Validation failed with $violations violation(s)"
        exit 1
    fi

    log "INFO" "Validation passed for network: $network"
}

cmd_export() {
    local network="$1"

    validate_network "$network"

    local network_dir="$SECRETS_DIR/$network"

    if [[ ! -d "$network_dir" ]]; then
        log "ERROR" "No secrets configured for network: $network"
        exit 1
    fi

    log "INFO" "Exporting secrets for network: $network (env-safe format)"

    local passphrase
    passphrase=$(get_network_config "$network" "network-passphrase")
    local rpc_url
    rpc_url=$(get_network_config "$network" "rpc-url")

    cat <<EOF
# Environment variables for network: $network
# Generated by manage_secrets.sh at $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT commit this file to version control

export STELLAR_NETWORK="$network"
export STELLAR_NETWORK_PASSPHRASE="$passphrase"
export SOROBAN_RPC_URL="$rpc_url"
export SOROBAN_RPC_PASSPHRASE="$passphrase"

# Identity addresses (generated, not secrets)
EOF

    local identity_dir="$network_dir/identities"
    if [[ -d "$identity_dir" ]]; then
        for identity_path in "$identity_dir"/*/; do
            if [[ -d "$identity_path" ]]; then
                local identity_name
                identity_name=$(basename "$identity_path")
                local address=""
                if [[ -f "$identity_path/address.txt" ]]; then
                    address=$(cat "$identity_path/address.txt")
                fi
                echo "export ${identity_name^^}_ADDRESS=\"$address\""
            fi
        done
    fi
}

# ─── Main ────────────────────────────────────────────────────────────────────

main() {
    if [[ $# -lt 1 ]]; then
        usage
        exit 1
    fi

    local command="$1"
    shift

    case "$command" in
        init)
            local network="${1:-}"
            local force="false"
            for arg in "$@"; do
                case "$arg" in
                    --force) force="true" ;;
                esac
            done
            if [[ -z "$network" ]]; then
                log "ERROR" "Network name is required"
                usage
                exit 1
            fi
            cmd_init "$network" "$force"
            ;;
        generate)
            local network="${1:-}"
            local name="${2:-}"
            local key_type="ed25519"
            local force="false"
            shift 2 2>/dev/null || true
            for arg in "$@"; do
                case "$arg" in
                    --key-type) key_type="${1:-ed25519}" ;;
                    --force) force="true" ;;
                esac
            done
            cmd_generate "$network" "$name" "$key_type" "$force"
            ;;
        list)
            local network="${1:-}"
            if [[ -z "$network" ]]; then
                log "ERROR" "Network name is required"
                usage
                exit 1
            fi
            cmd_list "$network"
            ;;
        rotate)
            local network="${1:-}"
            local name="${2:-}"
            if [[ -z "$network" || -z "$name" ]]; then
                log "ERROR" "Network and identity name are required"
                usage
                exit 1
            fi
            cmd_rotate "$network" "$name"
            ;;
        validate)
            local network="${1:-}"
            if [[ -z "$network" ]]; then
                log "ERROR" "Network name is required"
                usage
                exit 1
            fi
            cmd_validate "$network"
            ;;
        export)
            local network="${1:-}"
            if [[ -z "$network" ]]; then
                log "ERROR" "Network name is required"
                usage
                exit 1
            fi
            cmd_export "$network"
            ;;
        -h|--help|help)
            usage
            ;;
        *)
            log "ERROR" "Unknown command: $command"
            usage
            exit 1
            ;;
    esac
}

main "$@"
